v1:
  model_path: "/kaggle/input/hf-ship-model/v1.engine"
  conf: 0.1
  img_size: 640
v2:
  model_path: "/kaggle/input/hf-ship-model/v2.engine"
  conf: 0.1
  img_size: 1024
v3:
  model_path: "/kaggle/input/hf-ship-model/v3.engine"
  conf: 0.1
  img_size: 1280