v1:
  model_path: "/kaggle/input/hf-ship-model/yolov7_v1.pt"
  conf: 0.1
  img_size: 1024
v7_x_fold0:
  model_path: "/kaggle/input/hf-ship-model/v7_x_fold0.pt"
  conf: 0.01
  img_size: 1024
v7_x_fold1:
  model_path: "/kaggle/input/hf-ship-model/v7_x_fold1.pt"
  conf: 0.01
  img_size: 1024
v7_x_fold2:
  model_path: "/kaggle/input/hf-ship-model/v7_x_fold2.pt"
  conf: 0.01
  img_size: 1024
v7_x_fold3:
  model_path: "/kaggle/input/hf-ship-model/v7_x_fold3.pt"
  conf: 0.01
  img_size: 1024
v7_x_fold4:
  model_path: "/kaggle/input/hf-ship-model/v7_x_fold4.pt"
  conf: 0.01
  img_size: 1024